name: My first workflow

on: push 

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
                  
          uses: actions/checkout@v4 

        - name: Welcome message
          run: echo "My actions"

        - name: Read file
          run: cat README.md  


                
