name: Generate ASCII 
on: push 

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
                  
          uses: actions/checkout@v4 

        - name: Install cowsay
          run: sudo apt-get install cowsay -y 
             

        - name: generate ASCII art 
          run: cowsay -f dragon "i am a whale" >> whale.txt


                
