name: Generate ASCII 
on: push 

jobs:
  build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
                  
          uses: actions/checkout@v4 

        - name: Executing Shell scipti
          run: |
            chmod +x shell.sh
            ./shell.sh

            
            
     
  build_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          run: sleep 10

        - name: checkout repo
          run: grep -i "whale" whale.txt
                              
               
            

                         
            
            
            
                            
                                     

                         
            
 
            
            
                            
            
            
            
                            
            


                
